import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: 'Poppins, sans-serif' }}>
        <Header />
        <main className="flex text-white min-h-screen flex-col w-full bg-[#12111A] py-4 md:py-8 gap-4 content">
          {children}
        </main>
       <Footer />
      </body>
    </html>
  );
}
